Repository LLeeJr/Virciety, pull requests merged in 2022-03, with the labels that each got.

#66 Post events improvements
  client/package-lock.json
  client/projects/data-lib/src/lib/data-lib.service.ts
  client/projects/event/src/app/event/event.component.ts
  client/projects/event/src/app/event/event.module.ts
  client/projects/event/src/app/service/gql-request-strings.ts
  client/projects/event/src/app/service/gql.service.ts
  client/projects/event/src/app/single-event/single-event.component.html
  client/projects/event/src/app/single-event/single-event.component.scss
  client/projects/event/src/app/single-event/single-event.component.spec.ts
  client/projects/event/src/app/single-event/single-event.component.ts
  client/projects/event/webpack.config.js
  client/projects/notification/src/app/notification/notification.component.html
  client/projects/notification/src/app/notification/notification.component.ts
  client/projects/post/src/app/model/post.ts
  client/projects/post/src/app/post/comment/comment.component.html
  client/projects/post/src/app/post/comment/comment.component.scss
  client/projects/post/src/app/post/comment/comment.component.ts
  client/projects/post/src/app/post/media/media.component.html
  client/projects/post/src/app/post/media/media.component.ts
  client/projects/post/src/app/post/post.component.html
  client/projects/post/src/app/post/post.component.ts
  client/projects/post/src/app/post/post.module.ts
  client/projects/post/src/app/post/single-post/single-post.component.html
  client/projects/post/src/app/post/single-post/single-post.component.scss
  client/projects/post/src/app/post/single-post/single-post.component.spec.ts
  client/projects/post/src/app/post/single-post/single-post.component.ts
  client/projects/post/src/app/service/gql-request-strings.ts
  client/projects/post/src/app/service/gql.service.ts
  client/projects/shell/src/app/app-routing.module.ts
  client/projects/shell/src/app/app.module.ts
  client/projects/shell/src/app/decl.d.ts
  client/projects/shell/src/app/home/home.component.html
  client/projects/shell/src/app/home/home.component.ts
  client/projects/shell/src/app/single-event/single-event.component.html
  client/projects/shell/src/app/single-event/single-event.component.scss
  client/projects/shell/src/app/single-event/single-event.component.spec.ts
  client/projects/shell/src/app/single-event/single-event.component.ts
  client/projects/shell/src/app/single-post/single-post.component.html
  client/projects/shell/src/app/single-post/single-post.component.scss
  client/projects/shell/src/app/single-post/single-post.component.spec.ts
  client/projects/shell/src/app/single-post/single-post.component.ts
  server/event-service/database/repo.go
  server/event-service/graph/generated/generated.go
  server/event-service/graph/resolvers/mutation.resolvers.go
  server/event-service/graph/resolvers/query.resolvers.go
  server/event-service/graph/schemas/query.graphql
  server/notifs-service/database/repo.go
  server/post-service/database/db_connect.go
  server/post-service/database/repo.go
  server/post-service/graph/generated/generated.go
  server/post-service/graph/model/models_gen.go
  server/post-service/graph/resolvers/mutation.resolvers.go
  server/post-service/graph/resolvers/query.resolvers.go
  server/post-service/graph/schemas/model.graphql
  server/post-service/graph/schemas/query.graphql
Labels: enhancement, frontend

#68 Comment Bug + Notification Enhancement
  client/projects/notification/src/app/notification/notification.component.ts
  client/projects/post/src/app/post/single-post/single-post.component.ts
Labels: bug, enhancement

#71 UI optimization
  client/projects/chat/src/app/chat/chat.component.scss
  client/projects/chat/src/app/chat/open-chat/open-chat.component.html
  client/projects/chat/src/app/chat/open-chat/open-chat.component.scss
  client/projects/notification/src/app/notification/notification.component.html
  client/projects/notification/src/app/notification/notification.component.scss
  client/projects/notification/src/app/notification/notification.component.ts
  client/projects/post/src/app/create-post/create-post.component.html
  client/projects/post/src/app/create-post/create-post.component.scss
  client/projects/post/src/app/post/single-post/single-post.component.html
  client/projects/post/src/app/post/single-post/single-post.component.scss
  client/projects/profile-viewer/src/app/profile-viewer/profile-picture-dialog.html
  client/projects/profile-viewer/src/app/profile-viewer/profile-viewer.component.html
  client/projects/profile-viewer/src/app/profile-viewer/profile-viewer.component.scss
  client/projects/shell/src/app/app.component.html
  client/projects/shell/src/app/app.component.scss
  client/projects/shell/src/app/app.component.ts
  client/projects/shell/src/app/single-post/single-post.component.scss
  client/projects/user/src/app/user/user.component.html
  client/projects/user/src/app/user/user.component.scss
  client/projects/user/src/app/user/user.component.ts
Labels: frontend, fix

#73 Add comments and update readme
  client/README.md
  server/dm-service/database/connector.go
  server/dm-service/database/repo.go
  server/dm-service/graph/resolver.go
  server/dm-service/graph/schema.resolvers.go
  server/dm-service/queue/consumer.go
  server/dm-service/queue/publisher.go
  server/dm-service/queue/util.go
  server/dm-service/server.go
  server/dm-service/util/util.go
  server/notifs-service/database/connector.go
  server/notifs-service/database/repo.go
  server/notifs-service/graph/resolver.go
  server/notifs-service/graph/schema.resolvers.go
  server/notifs-service/queue/consumer.go
  server/notifs-service/queue/publisher.go
  server/notifs-service/queue/util.go
  server/notifs-service/server.go
  server/user-service/database/connector.go
  server/user-service/database/repo.go
  server/user-service/graph/resolver.go
  server/user-service/graph/schema.resolvers.go
  server/user-service/queue/consumer.go
  server/user-service/queue/publisher.go
  server/user-service/queue/util.go
  server/user-service/server.go
Labels: documentation
